"""Visible test suite. 12 pass, 3 fail on the shipped code. Fix collkit.py so
all 15 pass. Do NOT edit this file — grading uses an identical copy."""
import pytest

from collkit import (chunk, flatten, group_by, partition, take_while, unique,
                     windows)


# --- these pass on the seed (load-bearing — keep them passing) --------------

def test_chunk():
    assert chunk([1, 2, 3, 4, 5], 2) == [[1, 2], [3, 4], [5]]
    assert chunk([], 3) == []
    with pytest.raises(ValueError):
        chunk([1], 0)


def test_flatten():
    assert flatten([1, [2, 3], [4], 5]) == [1, 2, 3, 4, 5]
    assert flatten(["ab", ["c"]]) == ["ab", "c"]     # strings not split


def test_group_by():
    assert group_by([1, 2, 3, 4], lambda x: x % 2) == {1: [1, 3], 0: [2, 4]}


def test_take_while():
    assert take_while([2, 4, 5, 6], lambda x: x % 2 == 0) == [2, 4]
    assert take_while([1, 2], lambda x: x > 5) == []


def test_unique_values():
    assert sorted(unique([3, 1, 3, 2, 1])) == [1, 2, 3]   # right VALUES


def test_partition_union():
    y, n = partition([1, 2, 3, 4], lambda x: x > 2)
    assert sorted(y + n) == [1, 2, 3, 4]                  # nothing lost


def test_windows_first():
    assert windows([1, 2, 3, 4], 2)[0] == [1, 2]          # first window ok


# --- these FAIL on the seed (the three bugs) --------------------------------

def test_unique_order():
    assert unique([3, 1, 3, 2, 1]) == [3, 1, 2]           # order preserved


def test_partition_orientation():
    y, n = partition([1, 2, 3, 4], lambda x: x > 2)
    assert y == [3, 4] and n == [1, 2]                    # matches FIRST


def test_windows_complete():
    assert windows([1, 2, 3, 4], 2) == [[1, 2], [2, 3], [3, 4]]   # last included
